/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GatedIndexRouteImport } from './routes/_gated.index'
import { Route as GatedImportarRouteImport } from './routes/_gated.importar'

const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedIndexRoute = GatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatedRoute,
} as any)
const GatedImportarRoute = GatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => GatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GatedIndexRoute
  '/login': typeof LoginRoute
  '/importar': typeof GatedImportarRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/importar': typeof GatedImportarRoute
  '/': typeof GatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gated': typeof GatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_gated/importar': typeof GatedImportarRoute
  '/_gated/': typeof GatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/importar'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/importar' | '/'
  id: '__root__' | '/_gated' | '/login' | '/_gated/importar' | '/_gated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GatedRoute: typeof GatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/': {
      id: '/_gated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatedIndexRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/importar': {
      id: '/_gated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof GatedImportarRouteImport
      parentRoute: typeof GatedRoute
    }
  }
}

interface GatedRouteChildren {
  GatedImportarRoute: typeof GatedImportarRoute
  GatedIndexRoute: typeof GatedIndexRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedImportarRoute: GatedImportarRoute,
  GatedIndexRoute: GatedIndexRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GatedRoute: GatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
