/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GatedIndexRouteImport } from './routes/_gated.index'
import { Route as GatedAnaliseRouteImport } from './routes/_gated.analise'
import { Route as GatedAnoRouteImport } from './routes/_gated.ano'
import { Route as GatedCategoriasRouteImport } from './routes/_gated.categorias'
import { Route as GatedComoUsarRouteImport } from './routes/_gated.como-usar'
import { Route as GatedConfiguracoesRouteImport } from './routes/_gated.configuracoes'
import { Route as GatedContasRouteImport } from './routes/_gated.contas'
import { Route as GatedDiaRouteImport } from './routes/_gated.dia'
import { Route as GatedImportarRouteImport } from './routes/_gated.importar'
import { Route as GatedMesRouteImport } from './routes/_gated.mes'
import { Route as GatedMetasRouteImport } from './routes/_gated.metas'
import { Route as GatedPaineisRouteImport } from './routes/_gated.paineis'
import { Route as GatedRelatoriosRouteImport } from './routes/_gated.relatorios'
import { Route as GatedSemanaRouteImport } from './routes/_gated.semana'

const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedIndexRoute = GatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatedRoute,
} as any)
const GatedAnaliseRoute = GatedAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => GatedRoute,
} as any)
const GatedAnoRoute = GatedAnoRouteImport.update({
  id: '/ano',
  path: '/ano',
  getParentRoute: () => GatedRoute,
} as any)
const GatedCategoriasRoute = GatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => GatedRoute,
} as any)
const GatedComoUsarRoute = GatedComoUsarRouteImport.update({
  id: '/como-usar',
  path: '/como-usar',
  getParentRoute: () => GatedRoute,
} as any)
const GatedConfiguracoesRoute = GatedConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => GatedRoute,
} as any)
const GatedContasRoute = GatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => GatedRoute,
} as any)
const GatedDiaRoute = GatedDiaRouteImport.update({
  id: '/dia',
  path: '/dia',
  getParentRoute: () => GatedRoute,
} as any)
const GatedImportarRoute = GatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => GatedRoute,
} as any)
const GatedMesRoute = GatedMesRouteImport.update({
  id: '/mes',
  path: '/mes',
  getParentRoute: () => GatedRoute,
} as any)
const GatedMetasRoute = GatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => GatedRoute,
} as any)
const GatedPaineisRoute = GatedPaineisRouteImport.update({
  id: '/paineis',
  path: '/paineis',
  getParentRoute: () => GatedRoute,
} as any)
const GatedRelatoriosRoute = GatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => GatedRoute,
} as any)
const GatedSemanaRoute = GatedSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => GatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analise': typeof GatedAnaliseRoute
  '/ano': typeof GatedAnoRoute
  '/categorias': typeof GatedCategoriasRoute
  '/como-usar': typeof GatedComoUsarRoute
  '/configuracoes': typeof GatedConfiguracoesRoute
  '/contas': typeof GatedContasRoute
  '/dia': typeof GatedDiaRoute
  '/importar': typeof GatedImportarRoute
  '/mes': typeof GatedMesRoute
  '/metas': typeof GatedMetasRoute
  '/paineis': typeof GatedPaineisRoute
  '/relatorios': typeof GatedRelatoriosRoute
  '/semana': typeof GatedSemanaRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analise': typeof GatedAnaliseRoute
  '/ano': typeof GatedAnoRoute
  '/categorias': typeof GatedCategoriasRoute
  '/como-usar': typeof GatedComoUsarRoute
  '/configuracoes': typeof GatedConfiguracoesRoute
  '/contas': typeof GatedContasRoute
  '/dia': typeof GatedDiaRoute
  '/importar': typeof GatedImportarRoute
  '/mes': typeof GatedMesRoute
  '/metas': typeof GatedMetasRoute
  '/paineis': typeof GatedPaineisRoute
  '/relatorios': typeof GatedRelatoriosRoute
  '/semana': typeof GatedSemanaRoute
  '/': typeof GatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gated': typeof GatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_gated/analise': typeof GatedAnaliseRoute
  '/_gated/ano': typeof GatedAnoRoute
  '/_gated/categorias': typeof GatedCategoriasRoute
  '/_gated/como-usar': typeof GatedComoUsarRoute
  '/_gated/configuracoes': typeof GatedConfiguracoesRoute
  '/_gated/contas': typeof GatedContasRoute
  '/_gated/dia': typeof GatedDiaRoute
  '/_gated/importar': typeof GatedImportarRoute
  '/_gated/mes': typeof GatedMesRoute
  '/_gated/metas': typeof GatedMetasRoute
  '/_gated/paineis': typeof GatedPaineisRoute
  '/_gated/relatorios': typeof GatedRelatoriosRoute
  '/_gated/semana': typeof GatedSemanaRoute
  '/_gated/': typeof GatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/analise'
    | '/ano'
    | '/categorias'
    | '/como-usar'
    | '/configuracoes'
    | '/contas'
    | '/dia'
    | '/importar'
    | '/mes'
    | '/metas'
    | '/paineis'
    | '/relatorios'
    | '/semana'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/analise'
    | '/ano'
    | '/categorias'
    | '/como-usar'
    | '/configuracoes'
    | '/contas'
    | '/dia'
    | '/importar'
    | '/mes'
    | '/metas'
    | '/paineis'
    | '/relatorios'
    | '/semana'
    | '/'
  id:
    | '__root__'
    | '/_gated'
    | '/login'
    | '/reset-password'
    | '/_gated/analise'
    | '/_gated/ano'
    | '/_gated/categorias'
    | '/_gated/como-usar'
    | '/_gated/configuracoes'
    | '/_gated/contas'
    | '/_gated/dia'
    | '/_gated/importar'
    | '/_gated/mes'
    | '/_gated/metas'
    | '/_gated/paineis'
    | '/_gated/relatorios'
    | '/_gated/semana'
    | '/_gated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GatedRoute: typeof GatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/': {
      id: '/_gated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatedIndexRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/analise': {
      id: '/_gated/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof GatedAnaliseRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/ano': {
      id: '/_gated/ano'
      path: '/ano'
      fullPath: '/ano'
      preLoaderRoute: typeof GatedAnoRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/categorias': {
      id: '/_gated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof GatedCategoriasRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/como-usar': {
      id: '/_gated/como-usar'
      path: '/como-usar'
      fullPath: '/como-usar'
      preLoaderRoute: typeof GatedComoUsarRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/configuracoes': {
      id: '/_gated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof GatedConfiguracoesRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/contas': {
      id: '/_gated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof GatedContasRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/dia': {
      id: '/_gated/dia'
      path: '/dia'
      fullPath: '/dia'
      preLoaderRoute: typeof GatedDiaRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/importar': {
      id: '/_gated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof GatedImportarRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/mes': {
      id: '/_gated/mes'
      path: '/mes'
      fullPath: '/mes'
      preLoaderRoute: typeof GatedMesRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/metas': {
      id: '/_gated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof GatedMetasRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/paineis': {
      id: '/_gated/paineis'
      path: '/paineis'
      fullPath: '/paineis'
      preLoaderRoute: typeof GatedPaineisRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/relatorios': {
      id: '/_gated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof GatedRelatoriosRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/semana': {
      id: '/_gated/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof GatedSemanaRouteImport
      parentRoute: typeof GatedRoute
    }
  }
}

interface GatedRouteChildren {
  GatedAnaliseRoute: typeof GatedAnaliseRoute
  GatedAnoRoute: typeof GatedAnoRoute
  GatedCategoriasRoute: typeof GatedCategoriasRoute
  GatedComoUsarRoute: typeof GatedComoUsarRoute
  GatedConfiguracoesRoute: typeof GatedConfiguracoesRoute
  GatedContasRoute: typeof GatedContasRoute
  GatedDiaRoute: typeof GatedDiaRoute
  GatedImportarRoute: typeof GatedImportarRoute
  GatedMesRoute: typeof GatedMesRoute
  GatedMetasRoute: typeof GatedMetasRoute
  GatedPaineisRoute: typeof GatedPaineisRoute
  GatedRelatoriosRoute: typeof GatedRelatoriosRoute
  GatedSemanaRoute: typeof GatedSemanaRoute
  GatedIndexRoute: typeof GatedIndexRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedAnaliseRoute: GatedAnaliseRoute,
  GatedAnoRoute: GatedAnoRoute,
  GatedCategoriasRoute: GatedCategoriasRoute,
  GatedComoUsarRoute: GatedComoUsarRoute,
  GatedConfiguracoesRoute: GatedConfiguracoesRoute,
  GatedContasRoute: GatedContasRoute,
  GatedDiaRoute: GatedDiaRoute,
  GatedImportarRoute: GatedImportarRoute,
  GatedMesRoute: GatedMesRoute,
  GatedMetasRoute: GatedMetasRoute,
  GatedPaineisRoute: GatedPaineisRoute,
  GatedRelatoriosRoute: GatedRelatoriosRoute,
  GatedSemanaRoute: GatedSemanaRoute,
  GatedIndexRoute: GatedIndexRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GatedRoute: GatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
